apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ski-resort
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  sessionAffinity: None