apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ski-resort
  labels:
    app: backend
    component: api
type: Opaque
data:
  # These are base64 encoded values
  # Original values: username=admin, password=skiresort123
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: c2tpcmVzb3J0MTIz

  # JWT secret for API tokens (base64 encoded "ski-resort-jwt-secret-2024")
  JWT_SECRET: c2tpLXJlc29ydC1qd3Qtc2VjcmV0LTIwMjQ=

  # API key for internal communication (base64 encoded "api-key-ski-resort-internal")
  API_KEY: YXBpLWtleS1za2ktcmVzb3J0LWludGVybmFs