apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ski-resort
  labels:
    app: frontend
    component: web
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  sessionAffinity: None