apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ski-resort
  labels:
    app: frontend
    component: web
data:
  # React app configuration
  REACT_APP_API_URL: "/api"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_NAME: "Ski Resort Management"

  # Nginx configuration
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
    
        root /usr/share/nginx/html;
        index index.html index.htm;
    
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain text/css text/xml text/javascript 
                   application/javascript application/xml+rss application/json;
    
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
    
        # Handle React Router (SPA routing)
        location / {
            try_files $uri $uri/ /index.html;
    
            # Cache control for HTML files
            location ~* \.html$ {
                expires 5m;
                add_header Cache-Control "no-cache, public, must-revalidate";
            }
        }
    
        # API proxy to backend service
        location /api {
            proxy_pass http://backend-service:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
    
            # Timeout settings
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    
        # Health check endpoint (proxy to backend)
        location /health {
            proxy_pass http://backend-service:5000/health;
            access_log off;
        }
    
        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
    
            # Optional: Enable CORS for fonts
            location ~* \.(woff|woff2|ttf|eot)$ {
                add_header Access-Control-Allow-Origin "*";
            }
        }
    
        # Deny access to hidden files
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }
    }