apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: ski-resort
data:
  mongodb-port: "27017"
  mongodb-service: "mongodb-service"
  init-script: |
    db = db.getSiblingDB('ski_resort_db');
    db.createUser({
      user: 'admin',
      pwd: 'skiresort123',
      roles: [
        {
          role: 'readWrite',
          db: 'ski_resort_db'
        }
      ]
    });